layout_spectrum: 0.7368293
name: queer republic
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5635921
  lightness: 0.5338964
  saturation: 0.8691434
  rhythmicContrast: 0.4655761
  brandColors:
    - '#030507'
    - '#1F3545'
    - '#407191'
    - '#AEAEAE'
    - '#FDFDFD'
typography_spectrum: 0.1222597
