layout_spectrum: 0.7368293
typography_spectrum: 0.1222597
color:
  lightness: 0.5338964
  brandStrength: 0.5635921
  saturation: 0.8691434
  rhythmicContrast: 0.4655761
  brandColors:
    - '#0D0D12'
    - '#F0FBFF'
    - '#13A3D7'
    - '#40312B'
    - '#C6926D'
name: queer republic
