collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1222597
color:
  saturation: 0.8691434
  brandStrength: 0.5635921
  rhythmicContrast: 0.4655761
  brandColors:
    - '#030507'
    - '#1F3545'
    - '#407191'
    - '#AEAEAE'
    - '#FDFDFD'
  lightness: 0.5338964
layout_spectrum: 0.2851064
name: queer republic
